# Generated by Django 5.1.3 on 2024-12-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_makes", "0001_initial"),
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="carmake",
            field=models.ManyToManyField(to="car_makes.carmake"),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="workshops.category",
            ),
        ),
    ]
