# Generated by Django 5.1.3 on 2024-12-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_carmake_alter_service_category'),
        ('workshops', '0002_workshop_carmakes_alter_service_category'),
    ]

    operations = [
    ]
