# Generated by Django 5.1.3 on 2024-12-21 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default=201101234567, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a phone number in this format: '+201xxxxxxxxx'.", regex='^\\+20(10|11|12|15)[0-9]{8}$')]),
        ),
    ]
